# Use a lightweight web server image
FROM nginx:alpine

# Copy your HTML file into the server's default folder
COPY . /usr/share/nginx/html

# COPY custom configuration to change port to 3000
RUN sed -i 's/listen       80;/listen       3000;/' /etc/nginx/conf.d/default.conf

# Expose port 3000
EXPOSE 3000